
# SERVER CONFIG
server.port=8082
spring.application.name=item-service

# EUREKA CLIENT CONFIG
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka


# H2 DATABASE CONFIG
# Switch from in-memory to file-based H2 to persist data
spring.datasource.url=jdbc:h2:file:~/itemdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# H2 Console config
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ACTUATOR ENDPOINT
management.endpoints.web.exposure.include=*

# Zipkin endpoint
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

# Enable tracing
management.tracing.enabled=true

# Sample 100% of requests for development
management.tracing.sampling.probability=1.0

# UserName and Password for Customer - Service
# spring.security.user.name=admin
# spring.security.user.password=item123
